title: Pantry Pals
description: Team 1 project at UH Manoa
theme: jekyll-theme-cayman

# Optional GitHub Pages config
github:
  is_project_page: true
  repository_url: https://github.com/pantry-pals/pantry-pal
